const TOTAL_GLOVES_UK = 100;
const TOTAL_MASK_UK = 100;
const TOTAL_GLOVES_GERMANY = 50;
const TOTAL_MASK_GERMANY = 100;
const MASK_PRICE_UK = 65;
const MASK_PRICE_GERMANY = 100;
const GLOVES_PRICE_UK = 100;
const GLOVES_PRICE_GERMANY = 150;
const TRANSPORT_COST = 400;
const DISCOUNT_TRANSPORT_COST = 320;
const UK = "uk";
const GERMANY = "germany";
const GLOVES = 'gloves';
const MASK = 'mask';
const OUT_OF_STOCK = "OUT_OF_STOCK";

module.exports = {
  TOTAL_GLOVES_GERMANY,
  TOTAL_GLOVES_UK,
  TOTAL_MASK_GERMANY,
  TOTAL_MASK_UK,
  TRANSPORT_COST,
  DISCOUNT_TRANSPORT_COST,
  MASK_PRICE_GERMANY,
  MASK_PRICE_UK,
  GLOVES_PRICE_GERMANY,
  GLOVES_PRICE_UK,
  UK,
  GERMANY,
  OUT_OF_STOCK,
  GLOVES,
  MASK
}